from typing import Dict, List

H, L = "high", "low"


def _paper(names, year, cite, points):
    return {"names": names, "year": year, "cite": cite,
            "points": [{"when": when, "text": text} for when, text in points]}


BIBLIOGRAPHY: Dict[str, List[dict]] = {
    "hexaco": [
        _paper(["Ashton", "Lee"], 2007,
               "Ashton, M. C., & Lee, K. (2007). Empirical, theoretical, and practical advantages of the HEXACO model of personality structure. Personality and Social Psychology Review, 11(2), 150-166.",
               [({"Honesty-Humility": H}, "High Honesty-Humility reflects fairness and a reluctance to exploit others even when exploitation would go unpunished."),
                ({"Honesty-Humility": L}, "Low Honesty-Humility reflects a readiness to gain by exploiting others and a sense of entitlement to special treatment."),
                ({"Agreeableness": H}, "High Agreeableness reflects tolerance and forgiveness, a willingness to cooperate even with people who may have treated one unfairly."),
                ({"Agreeableness": L}, "Low Agreeableness reflects a readiness to feel anger and to retaliate in response to perceived mistreatment."),
                ({"Emotionality": H}, "High Emotionality reflects empathic concern, attachment to close others and avoidance of physical harm."),
                ({"Emotionality": L}, "Low Emotionality reflects emotional detachment, little worry in stressful situations and low need for emotional support.")]),
        _paper(["Lee", "Ashton"], 2018,
               "Lee, K., & Ashton, M. C. (2018). Psychometric properties of the HEXACO-100. Assessment, 25(5), 543-556.",
               [({"Extraversion": H}, "High Extraversion combines social self-esteem, social boldness, sociability and liveliness."),
                ({"Extraversion": L}, "Low Extraversion combines reserve in social settings, lower social self-esteem and less energy for social interaction."),
                ({"Conscientiousness": H}, "High Conscientiousness combines organization, diligence, perfectionism and prudence."),
                ({"Conscientiousness": L}, "Low Conscientiousness combines disorganization, lower persistence and more impulsive decision-making.")]),
        _paper(["Ashton", "Lee", "de Vries"], 2014,
               "Ashton, M. C., Lee, K., & de Vries, R. E. (2014). The HEXACO Honesty-Humility, Agreeableness, and Emotionality factors: A review of research and theory. Personality and Social Psychology Review, 18(2), 139-152.",
               [({"Honesty-Humility": H, "Agreeableness": H}, "Honesty-Humility and Agreeableness capture two complementary forms of cooperation: not exploiting others, and not retaliating against them."),
                ({"Honesty-Humility": L, "Agreeableness": L}, "Low Honesty-Humility with low Agreeableness combines a tendency to exploit with a tendency to retaliate.")]),
        _paper(["Zettler", "Thielmann", "Hilbig", "Moshagen"], 2020,
               "Zettler, I., Thielmann, I., Hilbig, B. E., & Moshagen, M. (2020). The nomological net of the HEXACO model of personality: A large-scale meta-analytic investigation. Perspectives on Psychological Science, 15(3), 723-760.",
               [({"Honesty-Humility": L}, "Across a large meta-analysis, low Honesty-Humility is the HEXACO factor most consistently linked to exploitative and antisocial outcomes."),
                ({"Openness": H}, "High Openness to Experience is linked to creativity, intellectual curiosity and unconventional interests."),
                ({"Openness": L}, "Low Openness to Experience is linked to conventional interests and a preference for familiar ideas."),
                ({"Conscientiousness": H}, "High Conscientiousness is the HEXACO factor most consistently linked to achievement-related and self-control outcomes.")]),
        _paper(["Espinoza", "Daljeet", "Meyer"], 2020,
               "Espinoza, J. A., Daljeet, K. N., & Meyer, J. P. (2020). Establishing the structure and replicability of personality profiles using the HEXACO-PI-R. Nature Human Behaviour, 4(7), 713-724.",
               [({}, "Five personality profiles replicate across large samples of HEXACO-PI-R respondents, so a person's pattern across the six factors is informative beyond any single factor.")]),
    ],
    "ambi": [
        _paper(["Yarkoni"], 2010,
               "Yarkoni, T. (2010). The abbreviation of personality, or how to measure 200 personality scales with 200 items. Journal of Research in Personality, 44(2), 180-198.",
               [({}, "The AMBI reproduces the scales of established inventories from a single short item set; the five domain scores here are built from its keys for the thirty NEO PI-R facets.")]),
        _paper(["Goldberg"], 1990,
               "Goldberg, L. R. (1990). An alternative 'description of personality': The Big-Five factor structure. Journal of Personality and Social Psychology, 59(6), 1216-1229.",
               [({"Conscientiousness": H}, "High conscientiousness in the Big-Five lexical structure reflects being organized, thorough, dependable and persevering."),
                ({"Conscientiousness": L}, "Low conscientiousness in the Big-Five lexical structure reflects being less organized and more spontaneous."),
                ({"Agreeableness": H}, "High agreeableness in the Big-Five lexical structure reflects being warm, cooperative, trusting and considerate."),
                ({"Agreeableness": L}, "Low agreeableness in the Big-Five lexical structure reflects being more critical, competitive and tough-minded.")]),
        _paper(["Goldberg", "Johnson", "Eber", "Hogan", "Ashton", "Cloninger", "Gough"], 2006,
               "Goldberg, L. R., Johnson, J. A., Eber, H. W., Hogan, R., Ashton, M. C., Cloninger, C. R., & Gough, H. G. (2006). The International Personality Item Pool and the future of public-domain personality measures. Journal of Research in Personality, 40(1), 84-96.",
               [({"Openness": H}, "High openness in IPIP scales reflects imagination, intellectual curiosity and aesthetic interest."),
                ({"Openness": L}, "Low openness in IPIP scales reflects practical, conventional interests and a preference for the familiar.")]),
        _paper(["DeYoung"], 2006,
               "DeYoung, C. G. (2006). Higher-order factors of the Big Five in a multi-informant sample. Journal of Personality and Social Psychology, 91(6), 1138-1151.",
               [({"Conscientiousness": H, "Agreeableness": H, "Neuroticism": L}, "Emotional stability, agreeableness and conscientiousness load on a higher-order Stability factor reflecting emotional, social and motivational self-regulation."),
                ({"Openness": H, "Extraversion": H}, "Openness and extraversion load on a higher-order Plasticity factor reflecting exploration and engagement with novelty.")]),
        _paper(["McCrae", "Costa"], 1987,
               "McCrae, R. R., & Costa, P. T. (1987). Validation of the five-factor model of personality across instruments and observers. Journal of Personality and Social Psychology, 52(1), 81-90.",
               [({}, "The five broad personality domains replicate across different instruments and across self-reports and observer ratings, so broad domain scores describe stable tendencies."),
                ({"Neuroticism": H}, "High Neuroticism reflects a tendency to experience worry, insecurity and negative emotions; observers who know the person tend to agree with the self-report."),
                ({"Neuroticism": L}, "Low Neuroticism reflects calmness, security and emotional stability; observers who know the person tend to agree with the self-report."),
                ({"Extraversion": H}, "High Extraversion reflects sociability, talkativeness and a liking for company and activity."),
                ({"Extraversion": L}, "Low Extraversion reflects reserve, quietness and a preference for fewer social demands.")]),
        _paper(["Gerlach", "Farb", "Revelle", "Amaral"], 2018,
               "Gerlach, M., Farb, B., Revelle, W., & Amaral, L. A. N. (2018). A robust data-driven approach identifies four personality types across four large data sets. Nature Human Behaviour, 2, 735-742.",
               [({}, "Four personality types replicate across large Big-Five-family data sets, although most people sit near the average type and the types are regions of higher density, not sharp categories."),
                ({"Neuroticism": L, "Extraversion": H, "Agreeableness": H, "Conscientiousness": H}, "The 'role model' type is low in neuroticism and high in the other four domains."),
                ({"Extraversion": H, "Agreeableness": L, "Conscientiousness": L}, "The 'self-centred' type is high in extraversion and below average in openness, agreeableness and conscientiousness.")]),
    ],
    "darktriad": [
        _paper(["Jones", "Paulhus"], 2014,
               "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): A brief measure of dark personality traits. Assessment, 21(1), 28-41.",
               [({"Machiavellianism": H}, "High Machiavellianism on the SD3 reflects strategic, calculating manipulation and a cynical view of others, with impulse control intact."),
                ({"Narcissism": H}, "High narcissism on the SD3 reflects grandiosity, entitlement and seeking of admiration."),
                ({"Psychopathy": H}, "High psychopathy on the SD3 reflects impulsivity, thrill-seeking and callousness."),
                ({"Machiavellianism": H, "Psychopathy": L}, "Machiavellianism differs from psychopathy in impulse control: Machiavellian individuals plan and delay, where psychopathic individuals act on impulse.")]),
        _paper(["Paulhus", "Williams"], 2002,
               "Paulhus, D. L., & Williams, K. M. (2002). The Dark Triad of personality: Narcissism, Machiavellianism, and psychopathy. Journal of Research in Personality, 36(6), 556-563.",
               [({"Machiavellianism": L, "Narcissism": L, "Psychopathy": L}, "The three traits share low agreeableness; scoring low on all three is consistent with a cooperative, agreeable interpersonal style."),
                ({"Machiavellianism": H, "Narcissism": H, "Psychopathy": H}, "The three traits overlap but are distinct, and all share low agreeableness: a tendency toward self-promotion, emotional coldness and duplicity.")]),
        _paper(["Persson", "Kajonius", "Garcia"], 2019,
               "Persson, B. N., Kajonius, P. J., & Garcia, D. (2019). Revisiting the structure of the Short Dark Triad. Assessment, 26(1), 3-16.",
               [({}, "SD3 Machiavellianism and psychopathy overlap heavily in structural analyses, so scores on those two scales should be read together.")]),
        _paper(["Furnham", "Richards", "Paulhus"], 2013,
               "Furnham, A., Richards, S. C., & Paulhus, D. L. (2013). The Dark Triad of personality: A 10 year review. Social and Personality Psychology Compass, 7(3), 199-216.",
               [({"Narcissism": H, "Psychopathy": L}, "Narcissism is the 'lightest' of the three traits and is more often linked to adaptive outcomes such as confidence and positive first impressions."),
                ({"Narcissism": L}, "Low subclinical narcissism is associated with modest self-presentation and less need for admiration.")]),
        _paper(["Muris", "Merckelbach", "Otgaar", "Meijer"], 2017,
               "Muris, P., Merckelbach, H., Otgaar, H., & Meijer, E. (2017). The malevolent side of human nature: A meta-analysis and critical review of the literature on the Dark Triad. Perspectives on Psychological Science, 12(2), 183-204.",
               [({"Psychopathy": H}, "In meta-analysis, psychopathy is the Dark Triad trait most strongly related to adverse interpersonal outcomes."),
                ({"Psychopathy": L}, "Low psychopathy scores are associated with behavioural restraint and concern for others.")]),
    ],
    "npi": [
        _paper(["Raskin", "Terry"], 1988,
               "Raskin, R., & Terry, H. (1988). A principal-components analysis of the Narcissistic Personality Inventory and further evidence of its construct validity. Journal of Personality and Social Psychology, 54(5), 890-902.",
               [({"Authority": H}, "The Authority component reflects dominance, assertiveness and seeing oneself as a leader."),
                ({"Exhibitionism": H}, "The Exhibitionism component reflects sensation seeking and enjoying being the centre of attention."),
                ({"Entitlement": H}, "The Entitlement component reflects ambition, need for power and expecting a great deal from others."),
                ({"Authority": L, "Entitlement": L}, "Low scores across the components reflect a modest, undemanding self-view.")]),
        _paper(["Ackerman", "Witt", "Donnellan", "Trzesniewski", "Robins", "Kashy"], 2011,
               "Ackerman, R. A., Witt, E. A., Donnellan, M. B., Trzesniewski, K. H., Robins, R. W., & Kashy, D. A. (2011). What does the Narcissistic Personality Inventory really measure? Assessment, 18(1), 67-87.",
               [({"Authority": H}, "Leadership/Authority content is the adaptive side of the NPI, linked to self-esteem and social potency."),
                ({"Entitlement": H}, "Entitlement/Exploitativeness content is the socially toxic side of the NPI, linked to interpersonal difficulties."),
                ({"Exploitativeness": H}, "Entitlement/Exploitativeness content is the socially toxic side of the NPI, linked to interpersonal difficulties."),
                ({"Exhibitionism": H}, "Grandiose Exhibitionism content reflects vanity, self-absorption and attention seeking."),
                ({"Vanity": H}, "Grandiose Exhibitionism content reflects vanity, self-absorption and attention seeking.")]),
        _paper(["Wetzel", "Leckelt", "Gerlach", "Back"], 2016,
               "Wetzel, E., Leckelt, M., Gerlach, T. M., & Back, M. D. (2016). Distinguishing subgroups of narcissists with latent class analysis. European Journal of Personality, 30(4), 374-389.",
               [({"Authority": H, "Exploitativeness": L}, "A subgroup marked mainly by agentic narcissism, without antagonistic features, shows the most adaptive characteristics."),
                ({"Authority": H, "Exploitativeness": H}, "A subgroup combining agentic and antagonistic narcissism shows the least adaptive characteristics.")]),
        _paper(["Back", "Kuefner", "Dufner", "Gerlach", "Rauthmann", "Denissen"], 2013,
               "Back, M. D., Kuefner, A. C. P., Dufner, M., Gerlach, T. M., Rauthmann, J. F., & Denissen, J. J. A. (2013). Narcissistic admiration and rivalry: Disentangling the bright and dark sides of narcissism. Journal of Personality and Social Psychology, 105(6), 1013-1037.",
               [({"Superiority": H}, "Narcissistic admiration, the assertive self-promotion of a grandiose self, is linked to charm and social success in the short term."),
                ({"Exploitativeness": H}, "Narcissistic rivalry, the antagonistic protection of the self, is linked to conflict and declining popularity over time."),
                ({"Superiority": L, "Exhibitionism": L}, "Low admiration-related narcissism is associated with less self-promotion and less striving for uniqueness.")]),
        _paper(["Campbell", "Bonacci", "Shelton", "Exline", "Bushman"], 2004,
               "Campbell, W. K., Bonacci, A. M., Shelton, J., Exline, J. J., & Bushman, B. J. (2004). Psychological entitlement: Interpersonal consequences and validation of a self-report measure. Journal of Personality Assessment, 83(1), 29-45.",
               [({"Entitlement": H}, "Psychological entitlement, a stable sense of deserving more than others, is linked to competitive choices and difficulty in close relationships."),
                ({"Entitlement": L}, "Low psychological entitlement is associated with equity-based expectations of what one deserves.")]),
    ],
    "dass": [
        _paper(["Lovibond", "Lovibond"], 1995,
               "Lovibond, P. F., & Lovibond, S. H. (1995). The structure of negative emotional states: Comparison of the Depression Anxiety Stress Scales (DASS) with the Beck Depression and Anxiety Inventories. Behaviour Research and Therapy, 33(3), 335-343.",
               [({"Depression": H}, "The DASS Depression scale measures low positive affect, loss of self-esteem and incentive, and hopelessness."),
                ({"Anxiety": H}, "The DASS Anxiety scale measures autonomic arousal, situational anxiety and the subjective experience of anxious affect."),
                ({"Stress": H}, "The DASS Stress scale measures persistent tension, irritability and a low threshold for becoming upset or frustrated."),
                ({"Depression": L}, "Low DASS Depression scores indicate few symptoms of low positive affect or hopelessness in the past week."),
                ({"Anxiety": L}, "Low DASS Anxiety scores indicate little autonomic arousal or situational anxiety in the past week."),
                ({"Stress": L}, "Low DASS Stress scores indicate little persistent tension or irritability in the past week.")]),
        _paper(["Clark", "Watson"], 1991,
               "Clark, L. A., & Watson, D. (1991). Tripartite model of anxiety and depression: Psychometric evidence and taxonomic implications. Journal of Abnormal Psychology, 100(3), 316-336.",
               [({"Anxiety": H, "Depression": L}, "In the tripartite model, physiological hyperarousal is specific to anxiety, while low positive affect is specific to depression; high arousal can occur without anhedonia."),
                ({"Depression": H, "Anxiety": L}, "In the tripartite model, low positive affect (anhedonia) is specific to depression and can occur without physiological hyperarousal."),
                ({"Depression": H, "Anxiety": H}, "In the tripartite model, depression and anxiety share a general distress factor, which explains why the two often rise together.")]),
        _paper(["Henry", "Crawford"], 2005,
               "Henry, J. D., & Crawford, J. R. (2005). The short-form version of the Depression Anxiety Stress Scales (DASS-21): Construct validity and normative data in a large non-clinical sample. British Journal of Clinical Psychology, 44(2), 227-239.",
               [({"Depression": H, "Anxiety": H, "Stress": H}, "The three DASS scales share a general psychological distress factor in addition to their specific content."),
                ({"Depression": L, "Anxiety": L, "Stress": L}, "Low scores across the three DASS scales indicate low general psychological distress.")]),
        _paper(["Antony", "Bieling", "Cox", "Enns", "Swinson"], 1998,
               "Antony, M. M., Bieling, P. J., Cox, B. J., Enns, M. W., & Swinson, R. P. (1998). Psychometric properties of the 42-item and 21-item versions of the Depression Anxiety Stress Scales in clinical groups and a community sample. Psychological Assessment, 10(2), 176-181.",
               [({}, "The DASS distinguishes depression, anxiety and stress as separate dimensions in both clinical and community samples; it measures symptom severity and is not a diagnostic instrument.")]),
        _paper(["Crawford", "Henry"], 2003,
               "Crawford, J. R., & Henry, J. D. (2003). The Depression Anxiety Stress Scales (DASS): Normative data and latent structure in a large non-clinical sample. British Journal of Clinical Psychology, 42(2), 111-131.",
               [({"Stress": H, "Anxiety": L}, "Stress on the DASS is a distinct dimension of tension and irritability, separable from anxious arousal."),
                ({"Stress": H}, "DASS scores are continuous: elevated stress reflects more frequent tension and irritability, differing in degree and not in kind from lower scores.")]),
    ],
    "kims": [
        _paper(["Baer", "Smith", "Allen"], 2004,
               "Baer, R. A., Smith, G. T., & Allen, K. B. (2004). Assessment of mindfulness by self-report: The Kentucky Inventory of Mindfulness Skills. Assessment, 11(3), 191-206.",
               [({"Observing": H}, "Observing is the skill of noticing internal and external experience such as sensations, thoughts and emotions."),
                ({"Describing": H}, "Describing is the skill of putting observed experience into words without judgment."),
                ({"Describing": L}, "Low Describing is related to difficulty identifying and labelling feelings."),
                ({"Acting with Awareness": H}, "Acting with Awareness is the skill of engaging fully in the current activity with undivided attention."),
                ({"Acting with Awareness": L}, "Low Acting with Awareness reflects behaving on automatic pilot with attention elsewhere."),
                ({"Accepting without Judgment": H}, "Accepting without Judgment is the skill of allowing experience to be as it is without evaluating it; it is related to lower experiential avoidance."),
                ({"Accepting without Judgment": L}, "Low Accepting without Judgment reflects evaluating one's inner experience as good or bad and is related to more psychological symptoms.")]),
        _paper(["Baer", "Smith", "Hopkins", "Krietemeyer", "Toney"], 2006,
               "Baer, R. A., Smith, G. T., Hopkins, J., Krietemeyer, J., & Toney, L. (2006). Using self-report assessment methods to explore facets of mindfulness. Assessment, 13(1), 27-45.",
               [({"Observing": H, "Accepting without Judgment": L}, "In people without meditation experience, observing can be associated with more, not less, distress when it is not accompanied by a non-judging stance."),
                ({"Observing": L}, "Low Observing reflects attending less to internal and external sensations.")]),
        _paper(["Pearson", "Lawless", "Brown", "Bravo"], 2015,
               "Pearson, M. R., Lawless, A. K., Brown, D. B., & Bravo, A. J. (2015). Mindfulness and emotional outcomes: Identifying subgroups of college students using latent profile analysis. Personality and Individual Differences, 76, 33-38.",
               [({"Observing": H, "Accepting without Judgment": L}, "A 'judgmentally observing' subgroup, high on observing and low on non-judging, shows the least favourable emotional outcomes of the four mindfulness subgroups."),
                ({"Acting with Awareness": H, "Accepting without Judgment": H}, "A 'non-judgmentally aware' subgroup, high on awareness and non-judging, shows favourable emotional outcomes.")]),
        _paper(["Brown", "Ryan"], 2003,
               "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: Mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84(4), 822-848.",
               [({"Acting with Awareness": H}, "Present-centred attention and awareness are associated with greater well-being and more autonomous self-regulation."),
                ({"Acting with Awareness": L}, "Lower present-centred attention is associated with more automatic, less self-regulated behaviour.")]),
        _paper(["Baer", "Smith", "Lykins", "Button", "Krietemeyer", "Sauer", "Walsh", "Duggan", "Williams"], 2008,
               "Baer, R. A., Smith, G. T., Lykins, E., Button, D., Krietemeyer, J., Sauer, S., Walsh, E., Duggan, D., & Williams, J. M. G. (2008). Construct validity of the Five Facet Mindfulness Questionnaire in meditating and nonmeditating samples. Assessment, 15(3), 329-342.",
               [({"Describing": H, "Accepting without Judgment": H}, "Describing and non-judging are among the mindfulness facets most consistently related to psychological well-being.")]),
    ],
    "hsq": [
        _paper(["Martin", "Puhlik-Doris", "Larsen", "Gray", "Weir"], 2003,
               "Martin, R. A., Puhlik-Doris, P., Larsen, G., Gray, J., & Weir, K. (2003). Individual differences in uses of humor and their relation to psychological well-being: Development of the Humor Styles Questionnaire. Journal of Research in Personality, 37(1), 48-75.",
               [({"Affiliative": H}, "Affiliative humor, used to amuse others and ease relationships, is related to extraversion, self-esteem and relationship satisfaction."),
                ({"Self-Enhancing": H}, "Self-enhancing humor, a humorous outlook used to cope with stress, is related to lower depression and anxiety and higher well-being."),
                ({"Aggressive": H}, "Aggressive humor, such as sarcasm and put-downs, is related to hostility and lower agreeableness."),
                ({"Self-Defeating": H}, "Self-defeating humor, amusing others at one's own expense, is related to lower self-esteem and more depressive and anxious symptoms."),
                ({"Affiliative": L}, "Low affiliative humor reflects less use of joking to connect with others."),
                ({"Aggressive": L}, "Low aggressive humor reflects avoiding humor that disparages others.")]),
        _paper(["Galloway"], 2010,
               "Galloway, G. (2010). Individual differences in personal humor styles: Identification of prominent patterns and their associates. Personality and Individual Differences, 48(5), 563-567.",
               [({"Affiliative": H, "Self-Enhancing": H, "Aggressive": L, "Self-Defeating": L}, "People who are above average on the positive humor styles and below average on the negative styles form one of four recurring humor patterns."),
                ({"Affiliative": H, "Self-Enhancing": H, "Aggressive": H, "Self-Defeating": H}, "People who are above average on all four humor styles form one of four recurring humor patterns.")]),
        _paper(["Leist", "Mueller"], 2013,
               "Leist, A. K., & Mueller, D. (2013). Humor types show different patterns of self-regulation, self-esteem, and well-being. Journal of Happiness Studies, 14(2), 551-569.",
               [({"Self-Enhancing": H}, "Humor types that rely on self-enhancing humor show higher self-esteem and well-being."),
                ({"Self-Enhancing": L, "Affiliative": L}, "People who use little humor of any style show less favourable self-regulation and well-being than those who use self-enhancing humor.")]),
        _paper(["Kuiper", "Grimshaw", "Leite", "Kirsh"], 2004,
               "Kuiper, N. A., Grimshaw, M., Leite, C., & Kirsh, G. (2004). Humor is not always the best medicine: Specific components of sense of humor and psychological well-being. Humor, 17(1-2), 135-168.",
               [({"Self-Defeating": H}, "Self-defeating humor is associated with poorer self-evaluations and more negative affect, so more humor is not always better."),
                ({"Self-Defeating": L}, "Low self-defeating humor is associated with more positive self-evaluations.")]),
        _paper(["Schneider", "Voracek", "Tran"], 2018,
               "Schneider, M., Voracek, M., & Tran, U. S. (2018). 'A joke a day keeps the doctor away?' Meta-analytical evidence of differential associations of habitual humor styles with mental health. Scandinavian Journal of Psychology, 59(3), 289-300.",
               [({"Self-Enhancing": H}, "In meta-analysis, self-enhancing humor shows the strongest positive association with mental health of the four styles."),
                ({"Self-Defeating": H}, "In meta-analysis, self-defeating humor is associated with poorer mental health."),
                ({"Aggressive": H}, "In meta-analysis, aggressive humor is largely unrelated to mental health.")]),
    ],
    "gcbs": [
        _paper(["Brotherton", "French", "Pickering"], 2013,
               "Brotherton, R., French, C. C., & Pickering, A. D. (2013). Measuring belief in conspiracy theories: The Generic Conspiracist Beliefs Scale. Frontiers in Psychology, 4, 279.",
               [({"Government Malfeasance": H}, "The Government Malfeasance facet reflects belief that governments routinely engage in criminal conspiracies against their own citizens."),
                ({"Malevolent Global": H}, "The Malevolent Global Conspiracies facet reflects belief that small secret groups control world events."),
                ({"Extraterrestrial Coverup": H}, "The Extraterrestrial Cover-up facet reflects belief that evidence of alien contact is being concealed."),
                ({"Personal Wellbeing Threats": H}, "The Personal Well-being facet reflects belief in conspiracies involving disease, technology and mind control."),
                ({"Control of Information": H}, "The Control of Information facet reflects belief that organisations suppress and manipulate information."),
                ({"Government Malfeasance": L, "Malevolent Global": L}, "Low scores across the facets reflect a low level of generic conspiracist ideation.")]),
        _paper(["Frenken", "Imhoff"], 2021,
               "Frenken, M., & Imhoff, R. (2021). A uniform conspiracy mindset or differentiated reactions to specific conspiracy beliefs? Evidence from latent profile analyses. International Review of Social Psychology, 34(1), 27.",
               [({}, "Conspiracy beliefs form a closely knit network: people mostly differ in their overall degree of belief, not in which conspiracies they endorse.")]),
        _paper(["Imhoff", "Bruder"], 2014,
               "Imhoff, R., & Bruder, M. (2014). Speaking (un-)truth to power: Conspiracy mentality as a generalised political attitude. European Journal of Personality, 28(1), 25-43.",
               [({"Government Malfeasance": H, "Malevolent Global": H}, "Conspiracy mentality behaves as a stable, generalised attitude: people who suspect one powerful group of conspiring tend to suspect others, and it is tied to distrust of groups seen as powerful.")]),
        _paper(["Swami", "Barron", "Weis", "Voracek", "Stieger", "Furnham"], 2017,
               "Swami, V., Barron, D., Weis, L., Voracek, M., Stieger, S., & Furnham, A. (2017). An examination of the factorial and convergent validity of four measures of conspiracist ideation, with recommendations for researchers. PLoS ONE, 12(2), e0172617.",
               [({}, "The five-factor structure of the GCBS was not confirmed in a large independent sample, so the five facet scores are best read as shades of one overall tendency.")]),
        _paper(["Douglas", "Sutton", "Cichocka"], 2017,
               "Douglas, K. M., Sutton, R. M., & Cichocka, A. (2017). The psychology of conspiracy theories. Current Directions in Psychological Science, 26(6), 538-542.",
               [({"Control of Information": H}, "Conspiracy belief appears to be driven by epistemic motives (wanting understanding and certainty), existential motives (wanting control and security) and social motives."),
                ({"Personal Wellbeing Threats": H}, "Conspiracy belief is stronger when people feel anxious or powerless and want to regain a sense of control and security."),
                ({"Control of Information": L, "Personal Wellbeing Threats": L}, "Lower conspiracy belief is associated with feeling in control and with trust in established sources of information.")]),
    ],
    "riasec": [
        _paper(["Holland"], 1959,
               "Holland, J. L. (1959). A theory of vocational choice. Journal of Counseling Psychology, 6(1), 35-45.",
               [({"Realistic": H}, "The Realistic type prefers concrete, physical activity involving tools, machines and things."),
                ({"Investigative": H}, "The Investigative type prefers observing, analysing and solving abstract problems."),
                ({"Artistic": H}, "The Artistic type prefers unstructured, expressive and creative activity."),
                ({"Social": H}, "The Social type prefers informing, helping and developing other people."),
                ({"Enterprising": H}, "The Enterprising type prefers persuading, leading and pursuing organisational or economic goals."),
                ({"Conventional": H}, "The Conventional type prefers orderly, systematic work with data and clear procedures.")]),
        _paper(["Tracey", "Rounds"], 1993,
               "Tracey, T. J., & Rounds, J. (1993). Evaluating Holland's and Gati's vocational-interest models: A structural meta-analysis. Psychological Bulletin, 113(2), 229-246.",
               [({"Artistic": H, "Conventional": L}, "A structural meta-analysis supports the circular ordering of the six types, on which Artistic and Conventional sit opposite each other; a strong preference for one with a weak preference for the other is a consistent, well-differentiated pattern."),
                ({"Social": H, "Realistic": L}, "A structural meta-analysis supports the circular ordering of the six types, on which Social and Realistic sit opposite each other; a strong preference for one with a weak preference for the other is a consistent, well-differentiated pattern."),
                ({"Investigative": H, "Enterprising": L}, "A structural meta-analysis supports the circular ordering of the six types, on which Investigative and Enterprising sit opposite each other; a strong preference for one with a weak preference for the other is a consistent, well-differentiated pattern.")]),
        _paper(["Nauta"], 2010,
               "Nauta, M. M. (2010). The development, evolution, and status of Holland's theory of vocational personalities. Journal of Counseling Psychology, 57(1), 11-22.",
               [({}, "Decades of research support the six-type structure and show that fit between a person's interests and their environment relates modestly to satisfaction.")]),
        _paper(["Prediger"], 1982,
               "Prediger, D. J. (1982). Dimensions underlying Holland's hexagon: Missing link between interests and occupations? Journal of Vocational Behavior, 21(3), 259-287.",
               [({"Social": H, "Realistic": L}, "Holland's hexagon is underpinned by a People versus Things dimension; high Social with low Realistic interest falls at the People end."),
                ({"Realistic": H, "Social": L}, "Holland's hexagon is underpinned by a People versus Things dimension; high Realistic with low Social interest falls at the Things end."),
                ({"Conventional": H, "Artistic": L}, "Holland's hexagon is underpinned by a Data versus Ideas dimension; high Conventional with low Artistic interest falls toward the Data end.")]),
        _paper(["Perera", "McIlveen"], 2018,
               "Perera, H. N., & McIlveen, P. (2018). Vocational interest profiles: Profile replicability and relations with the STEM major choice and the Big-Five. Journal of Vocational Behavior, 106.",
               [({}, "Six replicable profiles of vocational interest emerge from RIASEC scores, combining a dominant interest area with a characteristic overall level of interest.")]),
    ],
    "attachment": [
        _paper(["Fraley", "Waller", "Brennan"], 2000,
               "Fraley, R. C., Waller, N. G., & Brennan, K. A. (2000). An item response theory analysis of self-report measures of adult attachment. Journal of Personality and Social Psychology, 78(2), 350-365.",
               [({}, "Adult attachment is best described by two continuous dimensions, anxiety and avoidance, on which people differ by degree."),
                ({"Anxious": H}, "Attachment anxiety reflects fear of rejection and abandonment and a strong need for closeness and reassurance."),
                ({"Avoidant": H}, "Attachment avoidance reflects discomfort with closeness and dependence and a preference for self-reliance."),
                ({"Anxious": L}, "Low attachment anxiety reflects little worry about rejection or abandonment."),
                ({"Avoidant": L}, "Low attachment avoidance reflects comfort with closeness and with depending on others.")]),
        _paper(["Fraley", "Heffernan", "Vicary", "Brumbaugh"], 2011,
               "Fraley, R. C., Heffernan, M. E., Vicary, A. M., & Brumbaugh, C. C. (2011). The Experiences in Close Relationships-Relationship Structures Questionnaire: A method for assessing attachment orientations across relationships. Psychological Assessment, 23(3), 615-625.",
               [({}, "Attachment anxiety and avoidance can differ across a person's relationships, so a general score describes a typical tendency and not every relationship.")]),
        _paper(["Bartholomew", "Horowitz"], 1991,
               "Bartholomew, K., & Horowitz, L. M. (1991). Attachment styles among young adults: A test of a four-category model. Journal of Personality and Social Psychology, 61(2), 226-244.",
               [({"Anxious": L, "Avoidant": L}, "The secure style combines a positive model of self with a positive model of others: comfort with both intimacy and autonomy."),
                ({"Anxious": H, "Avoidant": L}, "The preoccupied style combines a negative model of self with a positive model of others: seeking acceptance through closeness to valued others."),
                ({"Anxious": L, "Avoidant": H}, "The dismissing style combines a positive model of self with a negative model of others: protecting independence by avoiding close relationships."),
                ({"Anxious": H, "Avoidant": H}, "The fearful style combines a negative model of self with a negative model of others: wanting closeness while avoiding it for fear of rejection.")]),
        _paper(["Mikulincer", "Shaver", "Pereg"], 2003,
               "Mikulincer, M., Shaver, P. R., & Pereg, D. (2003). Attachment theory and affect regulation: The dynamics, development, and cognitive consequences of attachment-related strategies. Motivation and Emotion, 27(2), 77-102.",
               [({"Anxious": H}, "Attachment anxiety is associated with hyperactivating strategies: intensified efforts to gain proximity and heightened vigilance to signs of rejection."),
                ({"Avoidant": H}, "Attachment avoidance is associated with deactivating strategies: suppressing attachment needs and keeping emotional distance."),
                ({"Secure": H}, "Attachment security is associated with effective regulation of distress and constructive ways of seeking support.")]),
        _paper(["Vaillancourt-Morel", "Godbout", "Sabourin"], 2022,
               "Vaillancourt-Morel, M.-P., et al. (2022). A latent profile analysis of romantic attachment anxiety and avoidance. Journal of Marital and Family Therapy.",
               [({}, "Latent profile analysis of attachment anxiety and avoidance scores recovers secure, preoccupied, dismissive and fearful profiles in a community sample.")]),
    ],
    "fti": [
        _paper(["Brown", "Acevedo", "Fisher"], 2013,
               "Brown, L. L., Acevedo, B., & Fisher, H. E. (2013). Neural correlates of four broad temperament dimensions: Testing predictions for a novel construct of personality. PLoS ONE, 8(11), e78734.",
               [({"Explorer": H}, "The Curious/Energetic scale reflects novelty seeking, energy and curiosity, and is proposed to relate to the dopamine system."),
                ({"Builder": H}, "The Cautious/Social Norm Compliant scale reflects caution, orderliness and respect for social norms, and is proposed to relate to the serotonin system."),
                ({"Director": H}, "The Analytical/Tough-minded scale reflects analytical, direct and decisive thinking, and is proposed to relate to the testosterone system."),
                ({"Negotiator": H}, "The Prosocial/Empathetic scale reflects empathy, intuition and holistic thinking, and is proposed to relate to the estrogen and oxytocin systems.")]),
        _paper(["Fisher", "Island", "Rich", "Marchalik", "Brown"], 2015,
               "Fisher, H. E., Island, H. D., Rich, J., Marchalik, D., & Brown, L. L. (2015). Four broad temperament dimensions: Description, convergent validation correlations, and comparison with the Big Five. Frontiers in Psychology, 6, 1098.",
               [({"Explorer": H}, "The Curious/Energetic scale correlates with openness to experience and extraversion."),
                ({"Builder": H}, "The Cautious/Social Norm Compliant scale correlates with conscientiousness."),
                ({"Negotiator": H}, "The Prosocial/Empathetic scale correlates with agreeableness."),
                ({"Explorer": L}, "Low Curious/Energetic scores reflect a preference for the familiar over the novel."),
                ({"Builder": L}, "Low Cautious/Social Norm Compliant scores reflect less concern with rules, plans and convention."),
                ({"Director": L}, "Low Analytical/Tough-minded scores reflect a less systemizing, less competitive approach."),
                ({"Negotiator": L}, "Low Prosocial/Empathetic scores reflect less reliance on empathy and intuition when deciding.")]),
        _paper(["Fisher", "Rich", "Island", "Marchalik"], 2010,
               "Fisher, H. E., Rich, J., Island, H. D., & Marchalik, D. (2010). The second to fourth digit ratio: A measure of two hormonally-based temperament dimensions. Personality and Individual Differences, 49(7), 773-777.",
               [({"Director": H, "Negotiator": L}, "The Analytical/Tough-minded and Prosocial/Empathetic scales are proposed as two contrasting, hormonally linked styles of thinking."),
                ({"Negotiator": H, "Director": L}, "The Analytical/Tough-minded and Prosocial/Empathetic scales are proposed as two contrasting, hormonally linked styles of thinking.")]),
        _paper(["Cloninger"], 1987,
               "Cloninger, C. R. (1987). A systematic method for clinical description and classification of personality variants. Archives of General Psychiatry, 44(6), 573-588.",
               [({"Explorer": H, "Builder": L}, "Novelty seeking and harm avoidance are independent temperament dimensions; high novelty seeking with low harm avoidance describes an exploratory, uninhibited style."),
                ({"Builder": H, "Explorer": L}, "Novelty seeking and harm avoidance are independent temperament dimensions; low novelty seeking with high harm avoidance describes a cautious, orderly style.")]),
        _paper(["Shayesteh", "Fisher", "Boman", "Nylander"], 2023,
               "Shayesteh, A., Fisher, H., Boman, J., & Nylander, E. (2023). High risk sexual behaviour may be identified by a short version of the Fisher Temperament Inventory. Acta Dermato-Venereologica, 103, 18469.",
               [({}, "A short form of the Fisher Temperament Inventory has been applied outside the original research group; independent evidence for the four scales remains limited.")]),
    ],
}


def applicable_points(test_id: str, traits: List[str], bands: Dict[str, str]) -> List[dict]:
    out = []
    for paper in BIBLIOGRAPHY.get(test_id, []):
        for point in paper["points"]:
            when = point["when"]
            if not when or not (set(when) & set(traits)):
                continue
            if all(bands.get(t) == b for t, b in when.items()):
                out.append({"text": point["text"], "names": paper["names"], "year": paper["year"],
                            "label": _label(paper), "summary": _summary(test_id, paper)})
    return out


def general_points(test_id: str) -> List[dict]:
    return [{"text": point["text"], "names": paper["names"], "year": paper["year"], "label": _label(paper),
             "summary": _summary(test_id, paper)}
            for paper in BIBLIOGRAPHY.get(test_id, []) for point in paper["points"] if not point["when"]]


def _label(paper: dict) -> str:
    names = paper["names"]
    if len(names) == 1:
        who = names[0]
    elif len(names) == 2:
        who = f"{names[0]} & {names[1]}"
    else:
        who = f"{names[0]} et al."
    return f"{who} ({paper['year']})"


def all_authors() -> Dict[str, List[str]]:
    out = {}
    for test_id, papers in BIBLIOGRAPHY.items():
        seen = []
        for paper in papers:
            authors = paper["cite"].split(" (", 1)[0].strip()
            if authors not in seen:
                seen.append(authors)
        out[test_id] = seen
    return out


def references(test_id: str) -> List[str]:
    return [paper["cite"] for paper in BIBLIOGRAPHY.get(test_id, [])]


SUMMARIES = {
    ("hexaco", "Ashton", 2007): "A theoretical and empirical review arguing that lexical studies in many languages recover six, not five, personality factors. It sets out the HEXACO model, defines each factor, and interprets Honesty-Humility, Agreeableness and Emotionality in terms of reciprocal and kin altruism.",
    ("hexaco", "Lee", 2018): "A psychometric evaluation of the 100-item HEXACO-PI-R in a very large online sample and a student sample with observer reports. It reports the reliabilities of the six factor scales and their facets, their factor structure, and agreement between self-reports and reports by people who know the respondent well.",
    ("hexaco", "Ashton", 2014): "A review of a decade of research on the three HEXACO factors that differ most from the Big Five. It explains how Honesty-Humility and Agreeableness describe two separate forms of cooperation, and how Emotionality relates to empathy, attachment and harm avoidance.",
    ("hexaco", "Zettler", 2020): "A large-scale meta-analysis mapping how each HEXACO factor relates to outcomes across many domains of psychology. It shows which factor is the strongest correlate of each outcome domain, with Honesty-Humility standing out for exploitation and antisocial behaviour.",
    ("hexaco", "Espinoza", 2020): "Latent profile analyses of four independent samples of about 90,000 HEXACO-PI-R respondents each. A five-profile solution fitted well, replicated across the samples, and held across gender and age groups.",
    ("ambi", "Yarkoni", 2010): "Introduces the Analog to Multiple Broadband Inventories. Using a genetic algorithm on a large item pool, it shows that 181 items can reproduce scores on more than 200 scales from several established personality inventories with little loss of validity.",
    ("ambi", "Goldberg", 1990): "Three studies of trait-descriptive adjectives showing that five broad factors recur across different samples, rating procedures and methods of factor analysis. It is the standard demonstration of the Big-Five lexical structure.",
    ("ambi", "Goldberg", 2006): "Describes the International Personality Item Pool, a public-domain collection of personality items and scales, and how it lets researchers measure the constructs of commercial inventories freely. The AMBI items are drawn from this pool.",
    ("ambi", "DeYoung", 2006): "Using ratings from several informants per person, this study shows that the Big Five are not fully independent but form two higher-order factors: Stability (emotional stability, agreeableness, conscientiousness) and Plasticity (extraversion, openness).",
    ("ambi", "McCrae", 1987): "Compares self-reports with ratings by peers and across two kinds of instrument. The same five factors appeared in each, with substantial agreement between self and observers, supporting the five-factor model as a description of real, observable traits.",
    ("ambi", "Gerlach", 2018): "An analysis of four large questionnaire data sets totalling more than 1.5 million respondents. Using a clustering method with strict checks against spurious clusters, it identifies four personality types (average, reserved, self-centred and role model) defined by Big-Five trait patterns.",
    ("darktriad", "Jones", 2014): "Develops and validates the 27-item Short Dark Triad across four studies. The three nine-item subscales show the expected structure and relate as predicted to longer established measures and to informant reports.",
    ("darktriad", "Paulhus", 2002): "The paper that named the Dark Triad. In a student sample it shows that Machiavellianism, subclinical narcissism and subclinical psychopathy overlap but are distinct, and that the only Big-Five trait all three share is low agreeableness.",
    ("darktriad", "Persson", 2019): "Re-examines the structure of the Short Dark Triad with item-level and bifactor analyses. Machiavellianism and psychopathy items were hard to separate, while narcissism was more distinct, suggesting the first two share a common core.",
    ("darktriad", "Furnham", 2013): "A review of the first ten years of Dark Triad research covering measurement, workplace, educational, mating and antisocial outcomes. It concludes that the three traits have distinct correlates despite their overlap.",
    ("darktriad", "Muris", 2017): "A meta-analysis and critical review of the Dark Triad literature. The three traits were substantially intercorrelated, and psychopathy emerged as the strongest predictor of adverse psychosocial outcomes.",
    ("npi", "Raskin", 1988): "A principal-components analysis of the Narcissistic Personality Inventory in over a thousand respondents, yielding the 40-item version and seven components: Authority, Self-Sufficiency, Superiority, Exhibitionism, Exploitativeness, Vanity and Entitlement, with evidence of construct validity from observer ratings.",
    ("npi", "Ackerman", 2011): "Re-analyses the NPI and finds a three-factor structure: Leadership/Authority, Grandiose Exhibitionism and Entitlement/Exploitativeness. The first relates to adaptive outcomes and the last to maladaptive ones, so the total score mixes healthy and unhealthy content.",
    ("npi", "Wetzel", 2016): "Latent class analyses of three German samples and one US sample. Four subgroups recurred: low narcissists, moderate narcissists marked mainly by admiration, moderate narcissists marked by admiration and rivalry, and high narcissists. The admiration-only group was the most adaptive.",
    ("npi", "Back", 2013): "Proposes and tests, across seven studies, that grandiose narcissism has two dimensions: admiration (assertive self-enhancement) and rivalry (antagonistic self-protection). The two have different, often opposite, social consequences.",
    ("npi", "Campbell", 2004): "Develops the Psychological Entitlement Scale across nine studies and shows that entitlement predicts taking more than one's share, competitive choices in commons dilemmas, and selfishness in romantic relationships.",
    ("dass", "Lovibond", 1995): "Compares the DASS with the Beck Depression and Anxiety Inventories in a large student sample. The DASS scales showed a clean three-factor structure and separated depression from anxiety better than the Beck scales did.",
    ("dass", "Clark", 1991): "A review of the psychometric evidence on anxiety and depression. It proposes the tripartite model: a shared general distress factor, physiological hyperarousal specific to anxiety, and low positive affect (anhedonia) specific to depression.",
    ("dass", "Henry", 2005): "Tests the structure of the DASS-21 in a large UK non-clinical adult sample and provides normative data. The best-fitting model had the three specific scales plus a general distress factor common to all items.",
    ("dass", "Antony", 1998): "Examines the 42- and 21-item DASS in clinical groups with anxiety and mood disorders and in a community sample. The three-factor structure held, and the scales distinguished between the diagnostic groups as expected.",
    ("dass", "Crawford", 2003): "Provides UK adult normative data for the DASS and tests competing models of its structure in a large non-clinical sample. The three scales were reliable, and scores behaved as continuous dimensions of severity.",
    ("kims", "Baer", 2004): "Develops the 39-item Kentucky Inventory of Mindfulness Skills, measuring Observe, Describe, Act with Awareness and Accept without Judgment, drawing on dialectical behaviour therapy. It reports the structure and reliability and relations with other constructs in student and clinical samples.",
    ("kims", "Baer", 2006): "Factor-analyses the combined items of five mindfulness questionnaires in a large student sample and derives five facets. It reports that the Observe facet behaves differently in people without meditation experience.",
    ("kims", "Pearson", 2015): "A latent profile analysis of mindfulness facets in a large college sample. Four subgroups emerged: high mindfulness, low mindfulness, judgmentally observing and non-judgmentally aware, with the judgmentally observing group reporting the worst emotional outcomes.",
    ("kims", "Brown", 2003): "Develops the Mindful Attention Awareness Scale and shows, in correlational, experience-sampling and clinical-intervention studies, that present-centred attention relates to greater well-being and more self-regulated behaviour.",
    ("kims", "Baer", 2008): "Tests the five mindfulness facets in samples of meditators and non-meditators. Most facets were higher in meditators and related to better psychological well-being, supporting their construct validity.",
    ("hsq", "Martin", 2003): "Develops the 32-item Humor Styles Questionnaire in a large sample, with four eight-item scales: affiliative, self-enhancing, aggressive and self-defeating. The two benign styles related to better well-being and the self-defeating style to poorer well-being.",
    ("hsq", "Galloway", 2010): "A cluster analysis of Humor Styles Questionnaire scores identifying four patterns: above average on all styles, below average on all, high on the positive styles only, and high on the negative styles only. The clusters differed in personality and self-esteem.",
    ("hsq", "Leist", 2013): "Uses cluster analysis to identify three humor types (endorsers, humor deniers and self-enhancers) and compares them. Types relying on self-enhancing humor showed better self-regulation, self-esteem and well-being.",
    ("hsq", "Kuiper", 2004): "Relates several components of sense of humor to well-being. Adaptive components related to better self-esteem and lower distress, while self-defeating and aggressive components did not, showing that humor is not uniformly beneficial.",
    ("hsq", "Schneider", 2018): "A meta-analysis of studies linking the four humor styles to mental health. Self-enhancing and affiliative humor related positively to mental health, self-defeating humor negatively, and aggressive humor was largely unrelated.",
    ("gcbs", "Brotherton", 2013): "Develops the 15-item Generic Conspiracist Beliefs Scale across four studies. It measures conspiracist ideation without naming specific events, covers five themes, and shows good reliability and validity.",
    ("gcbs", "Frenken", 2021): "Applies latent profile analysis to five data sets with 7,877 participants. Profiles differed mostly in overall degree of belief, supporting a general conspiracy mindset; the most strongly believing profiles were the smallest.",
    ("gcbs", "Imhoff", 2014): "Argues and shows across several studies that conspiracy mentality is a stable generalised political attitude, distinct from established attitudes such as authoritarianism, and tied to prejudice against groups perceived as powerful.",
    ("gcbs", "Swami", 2017): "Tests four measures of conspiracist ideation in 803 US adults. The proposed factor structure of the Generic Conspiracist Beliefs Scale was not confirmed, although the scale converged with endorsement of specific conspiracy theories.",
    ("gcbs", "Douglas", 2017): "A review proposing that people are drawn to conspiracy theories by epistemic, existential and social motives, and noting that the evidence suggests these beliefs often fail to satisfy those motives.",
    ("riasec", "Holland", 1959): "The original statement of Holland's theory: people can be characterised by their resemblance to a small number of vocational orientations, work environments can be classified the same way, and people seek environments that fit their orientation.",
    ("riasec", "Tracey", 1993): "A structural meta-analysis of over a hundred RIASEC correlation matrices. Holland's circular ordering of the six types fitted the data well and better than the competing hierarchical model.",
    ("riasec", "Nauta", 2010): "A review of fifty years of research on Holland's theory. It concludes that the six-type structure is well supported and that person-environment congruence relates modestly to satisfaction and persistence.",
    ("riasec", "Prediger", 1982): "Shows that two bipolar dimensions, Data versus Ideas and Things versus People, underlie Holland's hexagon and link interest scores to the tasks that characterise occupations.",
    ("riasec", "Perera", 2018): "A latent profile analysis of RIASEC scores in university students. Six interest profiles replicated across subsamples and differed in Big-Five traits and in choice of STEM majors.",
    ("attachment", "Fraley", 2000): "An item response theory analysis of four self-report attachment measures. It identifies the most informative items, producing the revised Experiences in Close Relationships scale, and supports measuring attachment on two continuous dimensions.",
    ("attachment", "Fraley", 2011): "Introduces a short questionnaire that measures attachment anxiety and avoidance separately for different relationships (mother, father, partner, friend) and shows that attachment varies meaningfully across relationships within the same person.",
    ("attachment", "Bartholomew", 1991): "Proposes and tests, in two studies using interviews and self- and friend-reports, a four-category model of adult attachment defined by positive or negative models of self and of others: secure, preoccupied, dismissing and fearful.",
    ("attachment", "Mikulincer", 2003): "A theoretical review of how the attachment system regulates emotion. It describes security-based strategies and the two secondary strategies, hyperactivation and deactivation, and their cognitive and emotional consequences.",
    ("attachment", "Vaillancourt-Morel", 2022): "A latent profile analysis of attachment anxiety and avoidance in a community sample of 1,663 and a clinical sample of 575. The community sample yielded secure, preoccupied, dismissive and fearful profiles; the clinical sample yielded three.",
    ("fti", "Brown", 2013): "Two functional MRI studies testing whether scores on the four Fisher Temperament Inventory scales correspond to activity in brain regions associated with the proposed neurochemical systems. Each scale was associated with regional activation consistent with its predicted system.",
    ("fti", "Fisher", 2015): "Describes the development of the Fisher Temperament Inventory in very large internet samples and reports its factor structure, reliability and correlations with the Big Five, which were moderate and in the expected directions.",
    ("fti", "Fisher", 2010): "Tests whether finger-length ratio, an indirect marker of prenatal hormone exposure, relates to two of the temperament scales. A relatively longer fourth finger went with higher Analytical/Tough-minded scores and the opposite pattern with higher Prosocial/Empathetic scores.",
    ("fti", "Cloninger", 1987): "Proposes a biosocial model of personality with three heritable temperament dimensions, novelty seeking, harm avoidance and reward dependence, each linked to a monoamine system, and uses their combinations to describe personality variants.",
    ("fti", "Shayesteh", 2023): "Applies a short form of the Fisher Temperament Inventory in a clinical setting to examine whether temperament scores relate to self-reported sexual risk behaviour, providing an application of the inventory by an independent clinical group.",
}


def _summary(test_id: str, paper: dict) -> str:
    return SUMMARIES.get((test_id, paper["names"][0], paper["year"]), "")
