from typing import Callable, Dict, List, Tuple

INSTRUMENTS: Dict[str, Dict[str, str]] = {
    "hexaco":     {"label": "HEXACO-PI-R", "citation": "Ashton & Lee, 2007"},
    "ambi":       {"label": "AMBI broad-bandwidth personality inventory", "citation": "Yarkoni, 2010"},
    "darktriad":  {"label": "Short Dark Triad (SD3)", "citation": "Jones & Paulhus, 2014"},
    "npi":        {"label": "Narcissistic Personality Inventory (NPI-40)", "citation": "Raskin & Terry, 1988"},
    "dass":       {"label": "Depression Anxiety Stress Scales (DASS-42)", "citation": "Lovibond & Lovibond, 1995"},
    "kims":       {"label": "Kentucky Inventory of Mindfulness Skills (KIMS)", "citation": "Baer, Smith & Allen, 2004"},
    "hsq":        {"label": "Humor Styles Questionnaire (HSQ)", "citation": "Martin et al., 2003"},
    "gcbs":       {"label": "Generic Conspiracist Beliefs Scale (GCBS)", "citation": "Brotherton, French & Pickering, 2013"},
    "riasec":     {"label": "Holland RIASEC vocational interest inventory", "citation": "Holland, 1959"},
    "attachment": {"label": "Experiences in Close Relationships (ECR)", "citation": "Fraley, Waller & Brennan, 2000"},
    "fti":        {"label": "Fisher Temperament Inventory (FTI)", "citation": "Brown, Acevedo & Fisher, 2013"},
}

TRAITS: Dict[str, Dict[str, Dict[str, str]]] = {
    "hexaco": {
        "Honesty-Humility": {
            "framework": "HEXACO Honesty-Humility factor; reciprocal-altruism (fairness) account",
            "high": "Elevated Honesty-Humility: low instrumental exploitation and low entitlement",
            "low": "Low Honesty-Humility: status-driven motivation and instrumental interpersonal strategy",
            "mid": "Mid-range Honesty-Humility: situationally contingent fairness norms",
        },
        "Emotionality": {
            "framework": "HEXACO Emotionality factor; kin-altruism and harm-avoidance account",
            "high": "Elevated Emotionality: heightened threat sensitivity and attachment-based dependence",
            "low": "Low Emotionality: reduced harm-avoidance and emotional detachment under stress",
            "mid": "Mid-range Emotionality: balanced threat appraisal and sentimentality",
        },
        "Extraversion": {
            "framework": "HEXACO Extraversion factor; social approach motivation and positive affectivity",
            "high": "Elevated Extraversion: strong social approach motivation and social self-esteem",
            "low": "Low Extraversion: reduced reward sensitivity to social stimulation",
            "mid": "Mid-range Extraversion: ambiverted social engagement",
        },
        "Agreeableness": {
            "framework": "HEXACO Agreeableness factor; tolerance-based reciprocal altruism and anger regulation",
            "high": "Elevated Agreeableness: high forgiveness and low trait anger reactivity",
            "low": "Low Agreeableness: retaliatory reactivity and low tolerance of perceived provocation",
            "mid": "Mid-range Agreeableness: conditional tolerance and selective forgiveness",
        },
        "Conscientiousness": {
            "framework": "HEXACO Conscientiousness factor; effortful control and executive self-regulation",
            "high": "Elevated Conscientiousness: strong effortful control and delay of gratification",
            "low": "Low Conscientiousness: reduced impulse control and weak goal maintenance",
            "mid": "Mid-range Conscientiousness: flexible self-regulation",
        },
        "Openness": {
            "framework": "HEXACO Openness to Experience factor; cognitive exploration and need for cognition",
            "high": "Elevated Openness: high need for cognition and aesthetic absorption",
            "low": "Low Openness: preference for cognitive closure and conventional schemas",
            "mid": "Mid-range Openness: selective cognitive exploration",
        },
    },
    "ambi": {
        "Neuroticism": {
            "framework": "Five-Factor Neuroticism; negative emotionality and stress reactivity",
            "high": "High Neuroticism: proneness to worry, tension and negative affect under stress",
            "low": "Low Neuroticism: emotional stability and low stress reactivity",
            "mid": "Moderate Neuroticism: average emotional reactivity",
        },
        "Extraversion": {
            "framework": "Five-Factor Extraversion; sociability, assertiveness and positive emotionality",
            "high": "High Extraversion: sociability, assertiveness and positive emotionality",
            "low": "Low Extraversion: reserve, lower need for social stimulation",
            "mid": "Moderate Extraversion: ambiverted social engagement",
        },
        "Openness": {
            "framework": "Five-Factor Openness to Experience; cognitive exploration",
            "high": "High Openness: intellectual curiosity, imagination and aesthetic interest",
            "low": "Low Openness: practical, conventional interests and preference for familiarity",
            "mid": "Moderate Openness: bounded curiosity",
        },
        "Agreeableness": {
            "framework": "Five-Factor Agreeableness; prosocial orientation and empathic concern",
            "high": "High Agreeableness: trust, cooperation and empathic concern",
            "low": "Low Agreeableness: scepticism of others and competitive orientation",
            "mid": "Moderate Agreeableness: conditional cooperation",
        },
        "Conscientiousness": {
            "framework": "Five-Factor Conscientiousness; executive self-regulation",
            "high": "High Conscientiousness: orderliness, self-discipline and goal persistence",
            "low": "Low Conscientiousness: spontaneity with weaker goal maintenance",
            "mid": "Moderate Conscientiousness: flexible self-discipline",
        },
    },
    "darktriad": {
        "Machiavellianism": {
            "framework": "Machiavellianism; strategic manipulation and cynical worldview (Christie & Geis)",
            "high": "Elevated Machiavellianism: strategic-calculating interpersonal orientation",
            "low": "Low Machiavellianism: trust-based, non-instrumental interpersonal orientation",
            "mid": "Mid-range Machiavellianism: situational strategic thinking",
        },
        "Narcissism": {
            "framework": "Subclinical grandiose narcissism; self-enhancement motivation",
            "high": "Elevated subclinical narcissism: grandiose self-enhancement and admiration seeking",
            "low": "Low subclinical narcissism: modest self-appraisal with little self-enhancement bias",
            "mid": "Mid-range subclinical narcissism: moderate self-enhancement",
        },
        "Psychopathy": {
            "framework": "Subclinical psychopathy; disinhibition and affective callousness",
            "high": "Elevated subclinical psychopathy: disinhibition and reduced affective empathy",
            "low": "Low subclinical psychopathy: intact affective empathy and behavioral restraint",
            "mid": "Mid-range subclinical psychopathy: moderate impulsivity with preserved empathy",
        },
    },
    "npi": {
        "Authority": {
            "framework": "NPI Leadership/Authority facet; agentic narcissism and social dominance",
            "high": "Elevated Authority: agentic dominance and leadership self-schema",
            "low": "Low Authority: low dominance motivation and deference in status hierarchies",
            "mid": "Mid-range Authority: situational leadership assertion",
        },
        "Self-Sufficiency": {
            "framework": "NPI Self-Sufficiency facet; autonomy and self-reliance",
            "high": "Elevated Self-Sufficiency: strong autonomous self-reliance",
            "low": "Low Self-Sufficiency: reliance on external guidance and validation",
            "mid": "Mid-range Self-Sufficiency: interdependent self-reliance",
        },
        "Superiority": {
            "framework": "NPI Superiority facet; downward social comparison and grandiosity",
            "high": "Elevated Superiority: grandiose self-concept sustained by downward social comparison",
            "low": "Low Superiority: non-grandiose, realistic self-appraisal",
            "mid": "Mid-range Superiority: moderate positive self-regard",
        },
        "Exhibitionism": {
            "framework": "NPI Grandiose Exhibitionism facet; attention-seeking and self-presentation",
            "high": "Elevated Exhibitionism: attention-seeking self-presentation",
            "low": "Low Exhibitionism: low need for attention and reserved self-presentation",
            "mid": "Mid-range Exhibitionism: selective self-display",
        },
        "Exploitativeness": {
            "framework": "NPI Entitlement/Exploitativeness facet; antagonistic narcissism",
            "high": "Elevated Exploitativeness: instrumental use of others and interpersonal antagonism",
            "low": "Low Exploitativeness: reciprocity-based interpersonal ethic",
            "mid": "Mid-range Exploitativeness: occasional instrumental influence",
        },
        "Vanity": {
            "framework": "NPI Vanity facet; appearance-contingent self-worth",
            "high": "Elevated Vanity: appearance-contingent self-esteem",
            "low": "Low Vanity: self-worth decoupled from physical appearance",
            "mid": "Mid-range Vanity: moderate appearance investment",
        },
        "Entitlement": {
            "framework": "Psychological entitlement (Campbell et al., 2004); antagonistic narcissism",
            "high": "Elevated Entitlement: inflated expectations of deservingness",
            "low": "Low Entitlement: equity-based expectations of deservingness",
            "mid": "Mid-range Entitlement: proportionate expectations of deservingness",
        },
    },
    "dass": {
        "Depression": {
            "framework": "Tripartite model (Clark & Watson, 1991): positive-affect dimension specific to depression",
            "high": "Elevated depressive symptoms: anhedonia, low positive affect and hopelessness",
            "low": "Low depressive symptoms: preserved positive affect and hedonic capacity",
            "mid": "Moderate depressive symptoms: intermittent dysphoria and reduced hedonic tone",
        },
        "Anxiety": {
            "framework": "Tripartite model (Clark & Watson, 1991): physiological-arousal dimension specific to anxiety",
            "high": "Elevated anxiety: autonomic hyperarousal and situational apprehension",
            "low": "Low anxiety: low autonomic arousal and minimal fear responding",
            "mid": "Moderate anxiety: intermittent autonomic arousal",
        },
        "Stress": {
            "framework": "DASS Stress scale: nonspecific tension and irritability; general-distress dimension",
            "high": "Elevated stress: chronic tension, irritability and difficulty relaxing",
            "low": "Low stress: low tension reactivity and good arousal recovery",
            "mid": "Moderate stress: situational tension and frustration reactivity",
        },
    },
    "kims": {
        "Observing": {
            "framework": "KIMS Observe facet; interoceptive and exteroceptive attentional monitoring",
            "high": "High Observing: heightened interoceptive awareness and attentional monitoring",
            "low": "Low Observing: limited interoceptive awareness",
            "mid": "Moderate Observing: intermittent attentional monitoring",
        },
        "Describing": {
            "framework": "KIMS Describe facet; affect labeling and emotional granularity (inverse of alexithymia)",
            "high": "High Describing: strong affect labeling and emotional granularity",
            "low": "Low Describing: alexithymic difficulty identifying and verbalising internal states",
            "mid": "Moderate Describing: partial emotional granularity",
        },
        "Acting with Awareness": {
            "framework": "KIMS Act with Awareness facet; sustained attention versus automatic pilot and mind-wandering",
            "high": "High Acting with Awareness: sustained present-moment attention and low mind-wandering",
            "low": "Low Acting with Awareness: automatic-pilot responding and frequent mind-wandering",
            "mid": "Moderate Acting with Awareness: fluctuating attentional presence",
        },
        "Accepting without Judgment": {
            "framework": "KIMS Accept without Judgment facet; experiential acceptance versus experiential avoidance",
            "high": "High non-judgmental acceptance: low experiential avoidance and low self-criticism",
            "low": "Low non-judgmental acceptance: experiential avoidance and self-critical evaluation of inner states",
            "mid": "Moderate non-judgmental acceptance: conditional acceptance of inner experience",
        },
    },
    "hsq": {
        "Affiliative": {
            "framework": "Affiliative humor (Martin et al., 2003); adaptive, relationship-enhancing",
            "high": "High affiliative humor: humor used for social bonding and tension reduction",
            "low": "Low affiliative humor: little use of humor for social bonding",
            "mid": "Moderate affiliative humor: situational social joking",
        },
        "Self-Enhancing": {
            "framework": "Self-enhancing humor (Martin et al., 2003); adaptive coping via cognitive reappraisal",
            "high": "High self-enhancing humor: humorous reappraisal as an emotion-focused coping strategy",
            "low": "Low self-enhancing humor: limited use of humor in coping with stressors",
            "mid": "Moderate self-enhancing humor: occasional humorous reappraisal",
        },
        "Aggressive": {
            "framework": "Aggressive humor (Martin et al., 2003); maladaptive, hostility-expressing",
            "high": "High aggressive humor: sarcasm and disparagement as indirect hostility",
            "low": "Low aggressive humor: avoidance of disparaging or hostile humor",
            "mid": "Moderate aggressive humor: occasional teasing with a hostile edge",
        },
        "Self-Defeating": {
            "framework": "Self-defeating humor (Martin et al., 2003); maladaptive ingratiation and defensive denial",
            "high": "High self-defeating humor: self-disparagement used for ingratiation and to mask negative affect",
            "low": "Low self-defeating humor: little self-disparagement for social approval",
            "mid": "Moderate self-defeating humor: occasional self-deprecation",
        },
    },
    "gcbs": {
        "Government Malfeasance": {
            "framework": "GCBS Government Malfeasance factor; institutional distrust",
            "high": "Elevated belief in government malfeasance: generalized institutional distrust",
            "low": "Low belief in government malfeasance: baseline institutional trust",
            "mid": "Moderate belief in government malfeasance: conditional institutional trust",
        },
        "Malevolent Global": {
            "framework": "GCBS Malevolent Global Conspiracies factor; hypersensitive agency detection",
            "high": "Elevated belief in malevolent global conspiracies: agency attribution to hidden coordinated groups",
            "low": "Low belief in malevolent global conspiracies: preference for situational and structural explanations",
            "mid": "Moderate belief in malevolent global conspiracies: selective agency attribution",
        },
        "Extraterrestrial Coverup": {
            "framework": "GCBS Extraterrestrial Cover-up factor; anomalous belief endorsement",
            "high": "Elevated extraterrestrial cover-up belief: anomalous belief endorsement",
            "low": "Low extraterrestrial cover-up belief: evidential skepticism toward anomalous claims",
            "mid": "Moderate extraterrestrial cover-up belief: open but uncommitted stance",
        },
        "Personal Wellbeing Threats": {
            "framework": "GCBS Personal Well-being factor; threat perception and perceived loss of control",
            "high": "Elevated personal well-being threat beliefs: heightened threat perception and compensatory control seeking",
            "low": "Low personal well-being threat beliefs: low perceived covert threat",
            "mid": "Moderate personal well-being threat beliefs: selective health and technology concern",
        },
        "Control of Information": {
            "framework": "GCBS Control of Information factor; epistemic mistrust",
            "high": "Elevated control-of-information belief: epistemic mistrust of official sources",
            "low": "Low control-of-information belief: epistemic trust in mainstream sources",
            "mid": "Moderate control-of-information belief: calibrated source skepticism",
        },
    },
    "riasec": {
        "Realistic": {
            "framework": "Holland Realistic type; things-oriented, sensorimotor interests",
            "high": "Strong Realistic interest: preference for concrete, tool- and things-oriented activity",
            "low": "Weak Realistic interest: low preference for manual or mechanical activity",
            "mid": "Moderate Realistic interest",
        },
        "Investigative": {
            "framework": "Holland Investigative type; ideas-oriented, analytic interests",
            "high": "Strong Investigative interest: analytic, inquiry-driven intrinsic motivation",
            "low": "Weak Investigative interest: low preference for abstract analysis",
            "mid": "Moderate Investigative interest",
        },
        "Artistic": {
            "framework": "Holland Artistic type; expressive, unstructured interests",
            "high": "Strong Artistic interest: need for self-expression and tolerance of ambiguity",
            "low": "Weak Artistic interest: preference for structured, defined tasks",
            "mid": "Moderate Artistic interest",
        },
        "Social": {
            "framework": "Holland Social type; people-oriented, helping interests",
            "high": "Strong Social interest: prosocial, helping-oriented vocational motivation",
            "low": "Weak Social interest: low preference for interpersonal helping roles",
            "mid": "Moderate Social interest",
        },
        "Enterprising": {
            "framework": "Holland Enterprising type; persuasive, status-oriented interests",
            "high": "Strong Enterprising interest: persuasive, leadership-oriented achievement motivation",
            "low": "Weak Enterprising interest: low preference for persuasion and competition",
            "mid": "Moderate Enterprising interest",
        },
        "Conventional": {
            "framework": "Holland Conventional type; data-oriented, structured interests",
            "high": "Strong Conventional interest: preference for order, procedure and data management",
            "low": "Weak Conventional interest: low tolerance for routine and procedural structure",
            "mid": "Moderate Conventional interest",
        },
    },
    "attachment": {
        "Anxious": {
            "framework": "Attachment anxiety dimension; internal working model of self",
            "high": "Elevated attachment anxiety: hyperactivation of the attachment system and fear of abandonment",
            "low": "Low attachment anxiety: positive working model of self and low rejection sensitivity",
            "mid": "Moderate attachment anxiety: situational proximity seeking",
        },
        "Avoidant": {
            "framework": "Attachment avoidance dimension; internal working model of others",
            "high": "Elevated attachment avoidance: deactivating strategies and compulsive self-reliance",
            "low": "Low attachment avoidance: comfort with intimacy and interdependence",
            "mid": "Moderate attachment avoidance: selective emotional distancing",
        },
        "Secure": {
            "framework": "Attachment security; secure-base script (Mikulincer & Shaver, 2016)",
            "high": "High attachment security: secure-base script and effective co-regulation",
            "low": "Low attachment security: insecure working models and limited co-regulation",
            "mid": "Moderate attachment security: partially consolidated secure-base script",
        },
    },
    "fti": {
        "Explorer": {
            "framework": "Fisher Curious/Energetic scale; dopaminergic novelty seeking",
            "high": "High Curious/Energetic temperament: novelty seeking and exploratory approach behavior",
            "low": "Low Curious/Energetic temperament: low novelty seeking and preference for predictability",
            "mid": "Moderate Curious/Energetic temperament",
        },
        "Builder": {
            "framework": "Fisher Cautious/Social Norm Compliant scale; serotonergic harm avoidance and conscientious conformity",
            "high": "High Cautious/Social Norm Compliant temperament: harm avoidance and adherence to social norms",
            "low": "Low Cautious/Social Norm Compliant temperament: low conformity and tolerance of risk",
            "mid": "Moderate Cautious/Social Norm Compliant temperament",
        },
        "Director": {
            "framework": "Fisher Analytical/Tough-minded scale; systemizing cognition and dominance",
            "high": "High Analytical/Tough-minded temperament: systemizing cognition and decisive dominance",
            "low": "Low Analytical/Tough-minded temperament: low systemizing and low competitive dominance",
            "mid": "Moderate Analytical/Tough-minded temperament",
        },
        "Negotiator": {
            "framework": "Fisher Prosocial/Empathetic scale; empathizing cognition and affiliative bonding",
            "high": "High Prosocial/Empathetic temperament: empathizing cognition and contextual, holistic thinking",
            "low": "Low Prosocial/Empathetic temperament: reduced empathic attunement",
            "mid": "Moderate Prosocial/Empathetic temperament",
        },
    },
}

Pattern = Tuple[Callable[[Dict[str, int]], bool], str, str, List[str]]


def _p(pct: Dict[str, int], name: str) -> int:
    return int(pct.get(name, 50))


PATTERNS: Dict[str, List[Pattern]] = {
    "hexaco": [
        (lambda p: _p(p, "Honesty-Humility") >= 65 and _p(p, "Agreeableness") >= 65,
         "Prosocial reciprocity profile: high fairness combined with high tolerance",
         "HEXACO altruism versus antagonism axis", ["Honesty-Humility", "Agreeableness"]),
        (lambda p: _p(p, "Honesty-Humility") <= 35 and _p(p, "Agreeableness") <= 35,
         "Antagonistic interpersonal profile: low fairness combined with low tolerance",
         "HEXACO altruism versus antagonism axis; overlap with Dark Triad variance", ["Honesty-Humility", "Agreeableness"]),
        (lambda p: _p(p, "Emotionality") >= 65 and _p(p, "Extraversion") <= 35,
         "Internalizing disposition: high threat sensitivity with low positive affectivity",
         "Internalizing spectrum; behavioral inhibition system (BIS) dominance", ["Emotionality", "Extraversion"]),
        (lambda p: _p(p, "Conscientiousness") <= 35 and _p(p, "Openness") >= 65,
         "Exploratory, low-constraint cognitive style",
         "Plasticity versus stability meta-traits (DeYoung)", ["Conscientiousness", "Openness"]),
    ],
    "ambi": [
        (lambda p: _p(p, "Neuroticism") <= 35 and _p(p, "Agreeableness") >= 65 and _p(p, "Conscientiousness") >= 65,
         "Stability meta-trait: emotional, social and motivational self-regulation",
         "Stability meta-trait (DeYoung, 2006)", ["Neuroticism", "Agreeableness", "Conscientiousness"]),
        (lambda p: _p(p, "Extraversion") >= 65 and _p(p, "Openness") >= 65,
         "Plasticity meta-trait: exploration and engagement with novelty",
         "Plasticity meta-trait (DeYoung, 2006)", ["Extraversion", "Openness"]),
        (lambda p: _p(p, "Neuroticism") >= 65 and _p(p, "Extraversion") <= 35,
         "Internalizing disposition: high negative emotionality with low positive emotionality",
         "Five-Factor Neuroticism and Extraversion; internalizing spectrum", ["Neuroticism", "Extraversion"]),
    ],
    "darktriad": [
        (lambda p: all(_p(p, t) >= 65 for t in ("Machiavellianism", "Narcissism", "Psychopathy")),
         "Elevated Dark Core: shared antagonistic disposition across all three traits",
         "Dark Factor of personality (D); callous-manipulative common core", ["Machiavellianism", "Narcissism", "Psychopathy"]),
        (lambda p: all(_p(p, t) <= 35 for t in ("Machiavellianism", "Narcissism", "Psychopathy")),
         "Low Dark Core: prosocial, low-antagonism disposition",
         "Dark Factor of personality (D); honesty-humility pole", ["Machiavellianism", "Narcissism", "Psychopathy"]),
        (lambda p: _p(p, "Machiavellianism") >= 65 and _p(p, "Psychopathy") <= 45,
         "Strategic rather than impulsive antagonism",
         "Machiavellian impulse control versus psychopathic disinhibition (Jones & Paulhus)", ["Machiavellianism", "Psychopathy"]),
    ],
    "npi": [
        (lambda p: _p(p, "Authority") >= 65 and _p(p, "Self-Sufficiency") >= 65
         and _p(p, "Exploitativeness") <= 50 and _p(p, "Entitlement") <= 50,
         "Adaptive agentic narcissism without antagonistic features",
         "Leadership/Authority versus Entitlement/Exploitativeness structure (Ackerman et al., 2011)",
         ["Authority", "Self-Sufficiency", "Exploitativeness", "Entitlement"]),
        (lambda p: _p(p, "Exploitativeness") >= 65 and _p(p, "Entitlement") >= 65,
         "Antagonistic narcissism: entitlement combined with exploitativeness",
         "Entitlement/Exploitativeness factor (Ackerman et al., 2011); narcissistic rivalry", ["Exploitativeness", "Entitlement"]),
        (lambda p: _p(p, "Exhibitionism") >= 65 and _p(p, "Vanity") >= 65,
         "Grandiose exhibitionism: appearance- and attention-contingent self-esteem",
         "Grandiose Exhibitionism factor (Ackerman et al., 2011); narcissistic admiration", ["Exhibitionism", "Vanity"]),
    ],
    "dass": [
        (lambda p: all(_p(p, t) >= 65 for t in ("Depression", "Anxiety", "Stress")),
         "Elevated general psychological distress across all three scales",
         "General distress / negative affectivity factor (Henry & Crawford, 2005)", ["Depression", "Anxiety", "Stress"]),
        (lambda p: _p(p, "Anxiety") >= 65 and _p(p, "Stress") >= 65 and _p(p, "Depression") < 65,
         "Arousal-dominant distress: hyperarousal and tension without marked anhedonia",
         "Tripartite model: hyperarousal with preserved positive affect", ["Anxiety", "Stress", "Depression"]),
        (lambda p: _p(p, "Depression") >= 65 and _p(p, "Anxiety") < 65,
         "Anhedonic-dominant distress: low positive affect without marked hyperarousal",
         "Tripartite model: low positive affect specific to depression", ["Depression", "Anxiety"]),
        (lambda p: all(_p(p, t) <= 35 for t in ("Depression", "Anxiety", "Stress")),
         "Low negative affectivity: emotional well-being across all three scales",
         "General distress / negative affectivity factor (Henry & Crawford, 2005)", ["Depression", "Anxiety", "Stress"]),
    ],
    "kims": [
        (lambda p: _p(p, "Observing") >= 65 and _p(p, "Accepting without Judgment") <= 35,
         "Self-focused attention without acceptance: risk of ruminative self-monitoring",
         "Observe-by-Nonjudge interaction; rumination versus mindful awareness",
         ["Observing", "Accepting without Judgment"]),
        (lambda p: _p(p, "Acting with Awareness") >= 65 and _p(p, "Accepting without Judgment") >= 65,
         "Decentered awareness: present-focused attention with experiential acceptance",
         "Decentering / cognitive defusion", ["Acting with Awareness", "Accepting without Judgment"]),
        (lambda p: _p(p, "Describing") <= 35 and _p(p, "Observing") <= 35,
         "Low emotional awareness: limited monitoring and labeling of internal states",
         "Alexithymia; levels of emotional awareness", ["Describing", "Observing"]),
    ],
    "hsq": [
        (lambda p: _p(p, "Affiliative") >= 65 and _p(p, "Self-Enhancing") >= 65,
         "Adaptive humor profile: humor as both social bonding and coping resource",
         "Adaptive (benign) humor styles; emotion-focused coping", ["Affiliative", "Self-Enhancing"]),
        (lambda p: _p(p, "Aggressive") >= 65 and _p(p, "Self-Defeating") >= 65,
         "Maladaptive humor profile: other-directed and self-directed disparagement",
         "Maladaptive (injurious) humor styles; hostility and low self-esteem correlates", ["Aggressive", "Self-Defeating"]),
        (lambda p: _p(p, "Self-Defeating") >= 65 and _p(p, "Self-Enhancing") <= 35,
         "Self-directed humor imbalance: self-disparagement without humorous reappraisal",
         "Self-defeating versus self-enhancing humor; defensive denial", ["Self-Defeating", "Self-Enhancing"]),
    ],
    "gcbs": [
        (lambda p: sum(p.values()) / max(len(p), 1) >= 65,
         "Generalized conspiracist ideation: a monological belief system",
         "Conspiracy mentality; monological belief system (Goertzel, 1994)", list(TRAITS["gcbs"].keys())),
        (lambda p: sum(p.values()) / max(len(p), 1) <= 35,
         "Low conspiracist ideation: default epistemic trust",
         "Conspiracy mentality; analytic thinking and epistemic trust", list(TRAITS["gcbs"].keys())),
        (lambda p: _p(p, "Government Malfeasance") >= 65 and _p(p, "Extraterrestrial Coverup") <= 35,
         "Differentiated skepticism: institutional distrust without anomalous belief",
         "Plausibility-graded conspiracy belief (Frenken & Imhoff, 2021)",
         ["Government Malfeasance", "Extraterrestrial Coverup"]),
    ],
    "riasec": [
        (lambda p: max(p.values()) - min(p.values()) >= 45,
         "High profile differentiation: clearly crystallized vocational interests",
         "Holland differentiation and vocational identity", list(TRAITS["riasec"].keys())),
        (lambda p: max(p.values()) - min(p.values()) <= 20,
         "Low profile differentiation: undifferentiated (flat) interest profile",
         "Holland differentiation; profile elevation", list(TRAITS["riasec"].keys())),
        (lambda p: (_p(p, "Social") + _p(p, "Artistic")) / 2 - (_p(p, "Realistic") + _p(p, "Conventional")) / 2 >= 25,
         "People-and-ideas orientation over things-and-data",
         "Prediger People/Things and Data/Ideas dimensions", ["Social", "Artistic", "Realistic", "Conventional"]),
        (lambda p: (_p(p, "Realistic") + _p(p, "Conventional")) / 2 - (_p(p, "Social") + _p(p, "Artistic")) / 2 >= 25,
         "Things-and-data orientation over people-and-ideas",
         "Prediger People/Things and Data/Ideas dimensions", ["Realistic", "Conventional", "Social", "Artistic"]),
    ],
    "attachment": [
        (lambda p: _p(p, "Anxious") >= 65 and _p(p, "Avoidant") >= 65,
         "Fearful-avoidant configuration: simultaneous hyperactivation and deactivation",
         "Bartholomew & Horowitz four-category model; approach-avoidance conflict", ["Anxious", "Avoidant"]),
        (lambda p: _p(p, "Anxious") >= 65 and _p(p, "Avoidant") < 65,
         "Preoccupied configuration: negative model of self with positive model of others",
         "Bartholomew & Horowitz four-category model; hyperactivating strategies", ["Anxious", "Avoidant"]),
        (lambda p: _p(p, "Avoidant") >= 65 and _p(p, "Anxious") < 65,
         "Dismissing-avoidant configuration: positive model of self with negative model of others",
         "Bartholomew & Horowitz four-category model; deactivating strategies", ["Avoidant", "Anxious"]),
        (lambda p: _p(p, "Anxious") <= 35 and _p(p, "Avoidant") <= 35,
         "Secure configuration: positive working models of self and others",
         "Bartholomew & Horowitz four-category model; secure-base script", ["Anxious", "Avoidant"]),
    ],
    "fti": [
        (lambda p: _p(p, "Explorer") >= 65 and _p(p, "Builder") <= 35,
         "Approach-dominant temperament: novelty seeking outweighs harm avoidance",
         "Novelty seeking versus harm avoidance (Cloninger); dopaminergic versus serotonergic systems",
         ["Explorer", "Builder"]),
        (lambda p: _p(p, "Builder") >= 65 and _p(p, "Explorer") <= 35,
         "Constraint-dominant temperament: harm avoidance outweighs novelty seeking",
         "Novelty seeking versus harm avoidance (Cloninger); dopaminergic versus serotonergic systems",
         ["Builder", "Explorer"]),
        (lambda p: _p(p, "Director") >= 65 and _p(p, "Negotiator") <= 35,
         "Systemizing-dominant cognitive style",
         "Empathizing-systemizing theory (Baron-Cohen)", ["Director", "Negotiator"]),
        (lambda p: _p(p, "Negotiator") >= 65 and _p(p, "Director") <= 35,
         "Empathizing-dominant cognitive style",
         "Empathizing-systemizing theory (Baron-Cohen)", ["Negotiator", "Director"]),
    ],
}

SUPPORT_NOTE = {
    "dass": ("The DASS is a screening measure of current symptom levels, not a diagnostic instrument. "
             "If distress is persistent or interfering with daily life, a qualified mental health "
             "professional can provide a proper assessment."),
}

LITERATURE = {
    "hexaco": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Ashton & Lee (2007); Lee & Ashton (2018)",
        "note": "Six-factor structure replicated across languages and samples.",
    },
    "ambi": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Yarkoni (2010); McCrae & Costa (1987)",
        "note": "Domains are scored from the published AMBI keys for the NEO PI-R facet scales.",
    },
    "darktriad": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Jones & Paulhus (2014); Persson, Kajonius & Garcia (2019)",
        "note": "Three-scale structure validated; the scales overlap substantially.",
    },
    "npi": {
        "grade": "moderate", "pattern_grade": "moderate",
        "sources": "Raskin & Terry (1988); Ackerman et al. (2011)",
        "note": "The seven short facets have modest reliability; a three-factor structure is better supported.",
    },
    "dass": {
        "grade": "strong", "pattern_grade": "strong",
        "sources": "Lovibond & Lovibond (1995); Henry & Crawford (2005); Clark & Watson (1991)",
        "note": "Three-scale structure and the tripartite distinction are well replicated.",
    },
    "kims": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Baer, Smith & Allen (2004); Baer et al. (2006)",
        "note": "Four-facet structure validated; profile patterns rest on Pearson et al. (2015).",
    },
    "hsq": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Martin et al. (2003)",
        "note": "Four humor styles and their well-being correlates are well replicated.",
    },
    "gcbs": {
        "grade": "moderate", "pattern_grade": "moderate",
        "sources": "Brotherton, French & Pickering (2013); Frenken & Imhoff (2021)",
        "note": "The total score is robust; the five separate factors are less stable across samples.",
    },
    "riasec": {
        "grade": "strong", "pattern_grade": "moderate",
        "sources": "Holland (1959); Nauta (2010)",
        "note": "Six-type interest structure is among the most replicated findings in vocational psychology.",
    },
    "attachment": {
        "grade": "strong", "pattern_grade": "strong",
        "sources": "Fraley, Waller & Brennan (2000); Bartholomew & Horowitz (1991); Mikulincer & Shaver (2016)",
        "note": "Anxiety and avoidance dimensions are well established.",
        "traits": {"Secure": {"grade": "moderate",
                              "note": "Security here is derived from the two ECR dimensions, not a separate scale."}},
    },
    "fti": {
        "grade": "limited", "pattern_grade": "limited",
        "sources": "Brown, Acevedo & Fisher (2013)",
        "note": "Neurochemical links are hypothesised from a small number of studies with little independent replication.",
    },
}
